name: Continuous Deployment

on:
  push:
    branches:
      - main

env:
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Railway and deploy
        run: |
          npm install -g @railway/cli
          railway up --service form_api_project
