name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install depedenci and implementasi
        run: |
          npm install
          npm install -g @railway/cli
          railway up --service form_api_project
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
