name: Continuous Deployment

on:
  push:
    branches:
      - main

env:
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Railway and deploy
        run: |
          npm install -g railway
          railway up
