name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install depedenci and implementasi
        run: |
          npm install
          npm run migrate up
          npm install -g @railway/cli
          railway up --service form_api_project
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
